### PR TITLE
Sandbox

### PR DESCRIPTION
**Pull request by jammiess**
## Description

Fixes a bug in the sandbox that causes it to break when a quotation mark is in the trigger message.

## Checklist

- [X] [Linked PR to corresponding issue in this repo](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)
- [X] Manually tested locally
- [X] Additional issue created in [docs repo](https://github.com/architus/docs.archit.us/issues) (if necessary)

### CODE REVIEW

**Comment by johnyburd** [comment]
you should do the same thing for the rest of them

**Comment by johnyburd** [comment]
cause rn a member could put quotes in their nickname
and break it

**Comment by jammiess** [comment]
@johnyburd Take a look at all the things I turned into go hooks and let me know if that's everything

**Comment by jammiess** [comment]
@johnyburd Pls review

**Review by johnyburd — APPROVED** [review]

**Pull request merged**
